export const mainnetRealms = [
  {
    symbol: "Ukraine",
    displayName: "Ukraine.SOL",
    programId: "gUAedF544JeE6NYbQakQvribHykUNgaPJqcgf3UQVnY",
    realmId: "5piGF94RbCqaogoFFWA9cYmt29qUpQejGCEjRKuwCz7d",
    bannerImage: "/realms/Ukraine/img/Flag_of_Ukraine.svg",
    ogImage: "/realms/Ukraine/img/Ukraine_Logo.png",
    sharedWalletId: "66pJhhESDjdeBBDdkKmxYYd7q6GUggYPWjxpMKNX39KV",
    sortRank: 3,
  },
  {
    symbol: "MNGO",
    displayName: "Mango DAO",
    programId: "GqTPL6qRf5aUuqscLh8Rg2HTxPUXfhhAXDptTLhp1t2J",
    realmId: "DPiH3H3c7t47BMxqTxLsuPQpEC6Kne8GA9VXbxpnZxFE",
    website: "https://mango.markets",
    keywords:
      "Mango Markets, REALM, Governance, Serum, SRM, Serum DEX, DEFI, Decentralized Finance, Decentralised Finance, Crypto, ERC20, Ethereum, Decentralize, Solana, SOL, SPL, Cross-Chain, Trading, Fastest, Fast, SerumBTC, SerumUSD, SRM Tokens, SPL Tokens",
    twitter: "@mangomarkets",
    ogImage: "https://trade.mango.markets/assets/icons/logo.svg",
    sortRank: 3,
  },
  {
    symbol: "MangoLiquidityDAO",
    displayName: "Mango Liquidity Council",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "DnWHRVRbA2XGwWth2da7iF3Q81cqRHhqJXSPS8J3G6fo",
    website: "https://mango.markets",
    keywords:
      "Mango Markets, REALM, Governance, Serum, SRM, Serum DEX, DEFI, Decentralized Finance, Decentralised Finance, Crypto, ERC20, Ethereum, Decentralize, Solana, SOL, SPL, Cross-Chain, Trading, Fastest, Fast, SerumBTC, SerumUSD, SRM Tokens, SPL Tokens",
    twitter: "@mangomarkets",
    ogImage: "https://trade.mango.markets/assets/icons/logo.svg",
  },
  {
    symbol: "MangolanaCouncil",
    displayName: "Mangolana Council",
    programId: "GqTPL6qRf5aUuqscLh8Rg2HTxPUXfhhAXDptTLhp1t2J",
    realmId: "Eb69t8zTkNbBViLRykbgBofr8PbwvZoAX4KicVcNNwkj",
    website: "https://mango.markets",
    keywords:
      "Mango Markets, REALM, Governance, Serum, SRM, Serum DEX, DEFI, Decentralized Finance, Decentralised Finance, Crypto, ERC20, Ethereum, Decentralize, Solana, SOL, SPL, Cross-Chain, Trading, Fastest, Fast, SerumBTC, SerumUSD, SRM Tokens, SPL Tokens",
    twitter: "@mangomarkets",
    ogImage: "/realms/MangoXSol/img/logo.svg",
  },
  {
    symbol: "DTP",
    displayName: "The Imperium of Rain",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "6orGiJYGXYk9GT2NFoTv2ZMYpA6asMieAqdek4YRH2Dn",
    ogImage: "/realms/RAIN/img/rain_logo.png",
  },
  {
    symbol: "UkraineUnchained",
    displayName: "#Unchain_Ukraine",
    programId: "gUAedF544JeE6NYbQakQvribHykUNgaPJqcgf3UQVnY",
    realmId: "HbdBjuyRtxJd4zCMCsvg64ajtxqk4vWogf8FtQpZcs54",
    bannerImage: "/realms/UkraineUnchained/img/ukraine_unchained_banner.jpeg",
    ogImage: "/realms/UkraineUnchained/img/ukraine_unchained.png",
    website: "https://unchain.fund",
    twitter: "@Unchainfund",
    sharedWalletId: "BnBe9uwucnLWpKqzgtvGU2aURRXezcqEVCoL8L6CeDgF",
  },
  {
    symbol: "WEZ",
    displayName: "Wezesha DAO",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "FEtF7V55LorZmUriVVobubPvLXoS7sfP3smzb5zR4BWz",
    website: "https://wezesha.co",
    keywords:
      "Wezesha DAO, Wezesha, Wezesha Coin, The Big Five NFTs Club, REALM, Governance, Serum, SRM, Serum DEX, DEFI, Decentralized Finance, Decentralised Finance, Crypto, SPL-TOKEN, Ethereum, Decentralize, Solana, SOL, SPL, Cross-Chain, Trading, Fastest, Fast, SerumBTC, SerumUSD, SRM Tokens, SPL Tokens",
    twitter: "@WezeshaCo",
    ogImage: "/realms/WezeshaDAO/img/wezesha_dao_logo.png",
  },
  {
    symbol: "BFNC",
    displayName: "BFNC DAO",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "36YGaNUYtRbaq1fHL4inLvHDxb7W28dBxWSna64v9Tea",
    website: "https://bigfivenftclub.com",
    keywords:
      "Big Five NFT Club DAO, BFNC DAO, Big Five Coin, The Big Five NFT Club, REALM, Governance, Serum, SRM, Serum DEX, DEFI, Decentralized Finance, Decentralised Finance, Crypto, SPL-TOKEN, Ethereum, Decentralize, Solana, SOL, SPL, Cross-Chain, Trading, Fastest, Fast, SerumBTC, SerumUSD, SRM Tokens, SPL Tokens",
    twitter: "@bigfivenftclub",
    ogImage: "/realms/BFNC/img/logo.png",
  },
  {
    symbol: "Wisdom Enterprising",
    displayName: "Wisdom Enterprising",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "4SGq4WekURkhi6Y3JfxN1ockV5qfwuPahFjB4sLe1bZx",
    website: "https://wisdomenterprising.com",
    keywords: "Wisdom Enterprising, realms.today, Decentralized, Web3, Wezesha",
    twitter: "@jakubsimek",
    ogImage: "/realms/WisdomEnterprising/img/WE.jpg",
  },
  {
    symbol: "ORCA",
    displayName: "Orca DAO",
    programId: "J9uWvULFL47gtCPvgR3oN7W357iehn5WF2Vn9MJvcSxz",
    realmId: "66Du7mXgS2KMQBUk6m9h3TszMjqZqdWhsG3Duuf69VNW",
    website: "https://www.orca.so/",
    twitter: "@orca_so",
    ogImage: "https://learn.orca.so/static/media/logomark.1ef55f8f.svg",
  },
  {
    symbol: "JET",
    displayName: "Jet DAO",
    programId: "JPGov2SBA6f7XSJF5R4Si5jEJekGiyrwP2m7gSEqLUs",
    realmId: "78TbURwqF71Qk4w1Xp6Jd2gaoQb6EC7yKBh5xDJmq6qh",
    website: "https://www.jetassociation.org/",
    twitter: "@jet_association",
    ogImage:
      "https://govern.jetassociation.org/img/jet_assoc/assoc_turbine.jpg",
  },
  {
    symbol: "The Sporagers",
    displayName: "The Sporagers",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "896vmJYkitEGhnBnRo8XxywUJu2qtgxidR9HXm5kjwrM",
    website: "https://www.thesporagers.io",
    twitter: "@TheSporagers",
    ogImage: "/realms/TheSporagers/img/the_sporagers.png",
    bannerImage: "/realms/TheSporagers/img/the_sporagers_banner.jpeg",
  },
  {
    symbol: "NFT Club Berlin",
    displayName: "NFT Club Berlin",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "E5DCxoF2vjzFeaDBi9kfFDZVoxrpe6nRFfKtm1J8Qdq7",
    ogImage: "/realms/NFTClubBerlin/img/logo.png",
    website: "http://nftclub.berlin",
    twitter: "@NFTClubBerlin",
  },
  {
    symbol: "POOR",
    displayName: "PoorDao (Famous Fox Edition)",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "12gEDQvesi9qSMoXcY1LSHxGqArUXZ2HemihyEShpoWf",
    website: "https://famousfoxes.com",
    twitter: "@PoorDao_FFF",
    ogImage: "/realms/PoorDao/img/archer.png",
  },
  {
    symbol: "CHIAO",
    displayName: "Chiao (Chimpions)",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "41SoCf3dmToE3YNJxAzz3GqNMp9SnzzYBH7cB7f1RJ82",
    website: "https://www.chimpions.co/",
    twitter: "@TheChimpions",
    ogImage: "/realms/Chiao/img/chiao.png",
  },
  {
    symbol: "PSY",
    displayName: "Psy Finance",
    programId: "GovHgfDPyQ1GwazJTDY2avSVY8GGcpmCapmmCsymRaGe",
    realmId: "FiG6YoqWnVzUmxFNukcRVXZC51HvLr6mts8nxcm7ScR8",
    website: "https://psyoptions.io",
    keywords:
      "PsyOptions, PsyFi, PsyFinance, REALM, Governance, Serum, SRM, DEX, DEFI, Decentralized Finance, Decentralised Finance, Crypto, ERC20, Ethereum, Decentralize, Solana, SOL, SPL, Cross-Chain, Trading, Fastest, Fast, SerumBTC, SerumUSD, Tokens, Options, Vaults",
    twitter: "@PsyOptions",
    ogImage:
      "https://user-images.githubusercontent.com/32071703/149460918-3694084f-2a37-4c95-93d3-b5aaf078d444.png",
  },
  {
    symbol: "SOCEAN",
    programId: "5hAykmD4YGcQ7Am3N7nC9kyELq6CThAkU82nhNKDJiCy",
    realmId: "759qyfKDMMuo9v36tW7fbGanL63mZFPNbhU7zjPrkuGK",
    website: "https://www.socean.fi",
    ogImage:
      "https://socean-git-enhancement-orca-price-feed-lieuzhenghong.vercel.app/static/media/socnRound.c466b499.png",
  },
  {
    symbol: "Governance",
    displayName: "Governance",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "FMEWULPSGR1BKVJK4K7xTjhG23NfYxeAn2bamYgNoUck",
    ogImage: "/realms/Governance/logo-spl-gov-1024.png",
  },
  {
    symbol: "Yield Farming",
    displayName: "Yield Farming",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "8eUUtRpBCg7sJ5FXfPUMiwSQNqC3FjFLkmS2oFPKoiBi",
  },
  {
    symbol: "SCTF1",
    programId: "gSF1T5PdLc2EutzwAyeExvdW27ySDtFp88ri5Aymah6",
    realmId: "EtZWAeFFRC5k6uesap1F1gkHFimsL2HqttVTNAeN86o8",
    ogImage: "/realms/SCTF1/img/sctf1.svg",
  },
  {
    symbol: "SERUM",
    programId: "AVoAYTs36yB5izAaBkxRG67wL1AMwG3vo41hKtUSb8is",
    realmId: "3MMDxjv1SzEFQDKryT7csAvaydYtrgMAc3L9xL9CVLCg",
    website: "https://www.projectserum.com/",
    ogImage:
      "https://assets.website-files.com/61284dcff241c2f0729af9f3/61285237ce2e301255d09108_logo-serum.png",
  },
  {
    symbol: "OMH",
    displayName: "Off My Head",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "4SsH1eg4zzwfRXBJjrKTY163U2UvW7n16B35pZVPxRpX",
    ogImage: "https://offmyhead.vercel.app/coin.png",
    website: "https://offmyhead.vercel.app",
    twitter: "@nft_omh",
  },
  {
    symbol: "FRIES",
    displayName: "Soltato",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "7wsrKBeTpqfcribDo34qr8rdSbqXbmQq9Fog2cVirK6C",
    ogImage:
      "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/FriCEbw1V99GwrJRXPnSQ6su2TabHabNxiZ3VNsVFPPN/logo.png",
    website: "https://soltato.io",
    twitter: "@Soltato_NFT",
  },
  {
    symbol: "Metaplex Foundation",
    displayName: "Metaplex Foundation",
    programId: "GmtpXy362L8cZfkRmTZMYunWVe8TyRjX5B7sodPZ63LJ",
    realmId: "2sEcHwzsNBwNoTM1yAXjtF1HTMQKUAXf8ivtdpSpo9Fv",
    ogImage: "/realms/metaplex/img/meta-white.png",
    website: "https://metaplex.com",
    twitter: "@metaplex",
  },
  {
    symbol: "Metaplex Genesis",
    displayName: "Metaplex Genesis",
    programId: "GMpXgTSJt2nJ7zjD1RwbT2QyPhKqD2MjAZuEaLsfPYLF",
    realmId: "Cdui9Va8XnKVng3VGZXcfBFF6XSxbqSi2XruMc7iu817",
    ogImage: "/realms/metaplex/img/meta-white.png",
    website: "https://metaplex.com",
    twitter: "@metaplex",
  },
  {
    symbol: "21DAO",
    displayName: "21DAO",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "Dn5yLFi6ZNhkD25CX4c8qq1MV3CC2vcrH2Qujfzy22rT",
    ogImage: "/realms/21DAO/img/21dao_icon.png",
    website: "https://21dao.xyz",
  },
  {
    symbol: "CDNL",
    displayName: "Cardinal",
    programId: "bqTjmeob6XTdfh12px2fZq4aJMpfSY1R1nHZ44VgVZD",
    realmId: "8o1tcKzRsEFAWYzi7Ge2cyotCaQW6vt5f2dy2HkWmemg",
    ogImage: "https://app.cardinal.so/assets/logo-colored.png",
    website: "https://www.cardinal.so",
    twitter: "@cardinal__so",
  },
  {
    symbol: "gSAIL",
    displayName: "GSAIL GOVERNANCE DAO",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "36fZRsuM3oXvb5VrEXXVmokbGnjADzVgKpW1pgQq7jXJ",
    ogImage:
      "https://raw.githubusercontent.com/solanasail/token-list/main/assets/mainnet/Gsai2KN28MTGcSZ1gKYFswUpFpS7EM9mvdR9c8f6iVXJ/logo.png",
    website: "https://www.solanasail.com/",
    twitter: "@SolanaSail",
  },
  {
    symbol: "FAFD",
    displayName: "Friends and Family DAO",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "371PRJu9vyU2U6WHcqorakWvz3wpfGSVhHr65BBSoaiN",
    ogImage: "/realms/FAFD/img/fafd_logo.png",
    website:
      "https://find-and-update.company-information.service.gov.uk/company/13753949",
  },
  {
    symbol: "$HOPE",
    displayName: "The Sanctuary",
    programId: "Ghope52FuF6HU3AAhJuAAyS2fiqbVhkAotb7YprL5tdS",
    realmId: "CS3HBXBdZ44g7FdZfgPAz6nSBe4FSThg6ANuVdowTT6G",
    ogImage: "/realms/hope/img/hope_logo.svg",
    website: "https://www.solsanctuary.io",
  },
  {
    symbol: "FANT",
    displayName: "Phantasia",
    programId: "5sGZEdn32y8nHax7TxEyoHuPS3UXfPWtisgm8kqxat8H",
    realmId: "4BNkheiMATVVcyJnGpjPbbPvFuKMx3cCDmkEbtnTz2iV",
    ogImage:
      "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/FANTafPFBAt93BNJVpdu25pGPmca3RfwdsDsRrT3LX1r/logo.png",
    website: "https://phantasia.app",
    twitter: "@PhantasiaSports",
  },
  {
    symbol: "MOOD",
    displayName: "Strangemood Foundation",
    programId: "smfjietFKFJ4Sbw1cqESBTpPhF4CwbMwN8kBEC1e5ui",
    realmId: "Dmn5q2SwkjZBKJGwULEWzK8zeZ2ES6JQvHKB297tAHXY",
    ogImage: "/realms/strangemood/img/logo.svg",
    website: "https://strangemood.org",
  },
  {
    symbol: "GRAPE",
    displayName: "GRAPE",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "By2sVGZXwfQq6rAiAM3rNPJ9iQfb5e2QhnF4YjJ4Bip",
    ogImage: "/realms/Grape/img/grape.png",
    website: "https://grapes.network/",
    twitter: "@grapeprotocol",
    sortRank: 3,
  },
  {
    symbol: "RED",
    displayName: "Realms Ecosystem DAO",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "C1tyCAEnbt4d63nbF36PGLc8gCC9DdtRXttXWGZwsAdF",
    ogImage: "/realms/RED/RED.png",
    website:
      "https://realms.notion.site/Realms-Ecosystem-DAO-RED-2b82519e797b4696968c5c909812f418",
    twitter: "@Realms_DAOs",
    sortRank: 2,
  },
  {
    symbol: "MonkeDAO",
    displayName: "MonkeDAO",
    programId: "GMnke6kxYvqoAXgbFGnu84QzvNHoqqTnijWSXYYTFQbB",
    realmId: "B1CxhV1khhj7n5mi5hebbivesqH9mvXr5Hfh2nD2UCh6",
    ogImage: "/realms/MonkeDAO/img/MonkeDAO_logo.png",
    website: "https://monkedao.io/",
    twitter: "@MonkeDAO",
  },
  {
    symbol: "MonkeDAOVote",
    displayName: "MonkeDAO Vote",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "Hcenib1A54LtG4V3TkG4MFYzcLzTqzYKFnttMxAq55c2",
    ogImage: "/realms/MonkeDAO/img/MonkeDAO_logo.png",
    website: "https://monkedao.io/",
    twitter: "@MonkeDAO",
  },
  {
    symbol: "MonkOG",
    displayName: "MonkOG DAO",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "39aX7mDZ1VLpZcPWstBhQBoqwNkhf5f1KDACguvrryi6",
    ogImage: "/realms/MonkOG/img/ogemoji.png",
    twitter: "@MonkOG_DAO",
  },
  {
    symbol: "NoGoal",
    displayName: "NoGoalDAO",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "3YdSnGzJbgyq5mGoFxu4RqmrUetUCEvyDkXEFy4oi6zd",
    ogImage: "/realms/NoGoal/img/ino-128.png",
    website: "https://nogoal.click/",
    twitter: "@NoGoalFacesNFT",
  },
  {
    symbol: "MNDE",
    displayName: "Marinade.Finance",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "3gmcbygQUUDgmtDtx41R7xSf3K4oFXrH9icPNijyq9pS",
    ogImage: "/realms/MNDE/img/mnde_logo.png",
    website: "https://marinade.finance/",
    twitter: "@marinadefinance",
  },
  {
    symbol: "COCK",
    displayName: "Chicken Tribe",
    programId: "GCockTxUjxuMdojHiABVZ5NKp6At8eTKDiizbPjiCo4m",
    realmId: "FuqmCzaTqH1QbokY3agcYQaJqoWog1UkSrcNCDBPXusu",
    ogImage:
      "https://chickentribe.com/_next/image?url=%2Fimages%2FChickenTribe_Team01.svg&w=128&q=75",
    website: "https://chickentribe.com/",
    twitter: "@ChickenTribe",
  },
  {
    symbol: "Kiwi",
    displayName: "Kiwi Kingd◎m",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "BkoiytgkhWBwyB7cwNPoMvi2DJ1Zxr51LMevaCBH5CiU",
    ogImage: "/realms/Kiwi/img/kiwi_logo.png",
    twitter: "@KiwiDAO",
  },
  {
    symbol: "$XAPE",
    displayName: "The Exiled Apes",
    programId: "Ghope52FuF6HU3AAhJuAAyS2fiqbVhkAotb7YprL5tdS",
    realmId: "2J1YbWH991rv7ZAsUVdV2cWXNf89XNuhqUsabaAP3Hc1",
    ogImage: "/realms/XAPE/img/logo_xape_nobckg.png",
    website: "https://exiledapes.academy",
    twitter: "@ExiledApes",
  },
  {
    symbol: "SF",
    displayName: "Succeed.Finance",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "CnnUUMnLcFL7ZxiGQoJaU8dgeCr3kwHn6Z1xpkWfQDHj",
    ogImage: "/realms/SF/img/succeedfinance.png",
    website: "https://www.succeed.finance",
    twitter: "@succeedfinance",
  },
  {
    symbol: "IADAO",
    displayName: "Investment Analyst DAO",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "BgezhGfctjcM8x5SsScCmX58txz8cUDikYp3ifk2vEqM",
    ogImage: "/realms/IADAO/img/IA-DAO_LOGO.png",
    website: "https://www.ia.finance",
  },
  {
    symbol: "WOOFDAO",
    displayName: "WOOF DAO",
    programId: "GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw",
    realmId: "DGnx2hbyT16bBMQFsVuHJJnnoRSucdreyG5egVJXqk8z",
    ogImage: "/realms/WoofDAO/img/wooflogo.png",
    keywords: "WOOF",
    website: "https://woofsolana.io/",
    twitter: "@WoofSolana",
  },
];
